name: Docker workflows

on:
  workflow_call:
    inputs:
      docker-label-documentation:
        required: false
        type: string
        default: ''
      docker-push:
        required: false
        type: boolean
        default: true
      publish-module-descriptor:
        required: false
        type: boolean
        default: false
    secrets:
      # these need to be non-required to allow anything here for forks
      # however, the sub-workflows will fail appropriately if these are not present, as applicable
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  set-shared-variables:
    name: Set shared variables
    runs-on: ubuntu-latest
    outputs:
      is-release: ${{ steps.logic.outputs.is-release }}
      docker-registry: ${{ steps.logic.outputs.docker-registry }}
      artifact-id: ${{ steps.vars.outputs.artifact-id }}
      repo-description: ${{ steps.vars.outputs.repo-description }}
    steps:
      - id: logic
        name: Determine default values
        run: |
          echo "We are on ref: $GITHUB_REF"
          if [[ "$GITHUB_REF" =~ ^refs/tags/v\d+\.. ]]; then
            echo "  We are on a tag vX.Y"
            echo "is-release=True" | tee -a $GITHUB_OUTPUT
            echo "docker-registry=folioorg" | tee -a $GITHUB_OUTPUT
          else
            echo "  We are not on a version tag"
            echo "is-release=False" | tee -a $GITHUB_OUTPUT
            echo "docker-registry=folioci" | tee -a $GITHUB_OUTPUT
          fi

      - id: vars
        name: Determine other variables
        env:
          DESCRIPTION: ${{ github.event.repository.description }}
        run: |
          echo "artifact-id=${GITHUB_REPOSITORY##*/}" | tee -a $GITHUB_OUTPUT
          # multi line description
          UUID=$(uuidgen)
          echo "repo-description<<$UUID" | tee -a $GITHUB_OUTPUT
          echo "$DESCRIPTION" | tee -a $GITHUB_OUTPUT
          echo "$UUID" | tee -a $GITHUB_OUTPUT

  version-number:
    needs: [set-shared-variables]
    uses: ./.github/workflows/docker-version-number.yml
    with:
      is-release: ${{ needs.set-shared-variables.outputs.is-release }}

  docker-publish:
    needs: [set-shared-variables, version-number]
    uses: ./.github/workflows/docker-publish.yml
    with:
      is-release: ${{ needs.set-shared-variables.outputs.is-release }}
      artifact-id: ${{ needs.set-shared-variables.outputs.artifact-id }}
      artifact-version: ${{ needs.version-number.outputs.version-number }}
      docker-registry: ${{ needs.set-shared-variables.outputs.docker-registry }}
      docker-push: ${{ inputs.docker-push }}
      docker-label-documentation: ${{ inputs.docker-label-documentation }}
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-description:
    name: Publish image description
    needs: [set-shared-variables, docker-publish]
    uses: ./.github/workflows/docker-description.yml
    with:
      artifact-id: ${{ needs.set-shared-variables.outputs.artifact-id }}
      docker-registry: ${{ needs.set-shared-variables.outputs.docker-registry }}
      repo-description: ${{ needs.set-shared-variables.outputs.repo-description }}
      publish-module-descriptor: ${{ inputs.publish-module-descriptor }}
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  report-testing-variables:
    needs: [set-shared-variables, version-number]
    uses: ./.github/workflows/docker-report-testing-variables.yml
    with:
      is-release: ${{ needs.set-shared-variables.outputs.is-release }}
      artifact-id: ${{ needs.set-shared-variables.outputs.artifact-id }}
      artifact-version: ${{ needs.version-number.outputs.version-number }}
      docker-push: ${{ inputs.docker-push }}
