name: Go lint errcheck

on:
  workflow_call:
    inputs:
      errcheck-excludes-file:
        required: false
        type: string

jobs:
  errcheck:
    name: Lint with errcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Install errcheck
        run: go install github.com/kisielk/errcheck@latest

      - name: Run errcheck
        env:
          EXCLUDE: ${{ inputs.errcheck-excludes-file }}
        run: |
          if [ -z "$EXCLUDE" ]; then
            errcheck ./...
          else
            errcheck -exclude "$EXCLUDE" ./...
          fi

